/*
// NOTE: All comments in this file were generated by AI.
//
/*
Author: Bryceson Gaoiran
Date: 2026-02-03
Overview: Prompts the user for a URL, generates a QR code image from that URL,
and saves both the QR image and the original URL to files.
Key highlights:
- Uses `inquirer` for interactive terminal prompting.
- Generates a PNG QR code via `qr-image` and streams it to `qr_img.png`.
- Persists the entered URL to `URL.txt` for record-keeping.
- Writes files asynchronously and handles basic prompt errors.
*/

// Import dependencies:
// - `inquirer` prompts the user in the terminal for input.
// - `qr-image` converts a string (URL) into a QR code image stream.
// - `fs` is Node's built-in file system module to read/write files.
import inquirer from "inquirer";
import qr from "qr-image";
import fs from "fs";

// Helper: validate a string is a well-formed URL using the WHATWG URL class.
function isValidUrl(s) {
  try {
    new URL(s);
    return true;
  } catch (_) {
    return false;
  }
}

// Centralized QR generation + file write logic so it can be used
// from the interactive prompt or from a CLI argument.
function generateFromUrl(url) {
  if (!isValidUrl(url)) {
    console.error("Error: Provided value is not a valid URL:", url);
    return;
  }

  // Inform the user what will be created (more friendly UX).
  console.log("Generating QR image and saving URL...\nOutput files: qr_img.png, URL.txt");

  const qr_svg = qr.image(url);
  qr_svg.pipe(fs.createWriteStream("qr_img.png"));

  fs.writeFile("URL.txt", url, (err) => {
    if (err) {
      console.error("Failed to write URL.txt:", err);
      return;
    }
    console.log("Done — QR image and URL saved.");
  });
}

// If a URL was passed as the first CLI argument, use it and skip the prompt.
const cliUrl = process.argv[2];
if (cliUrl) {
  generateFromUrl(cliUrl);
} else {
  // Prompt the user for a URL. `prompt` returns a Promise which resolves
  // with an `answers` object containing the user's responses.
  inquirer
    .prompt([
      {
        // The message shown to the user
        message: "Type in your URL: ",
        // The key name used to access the user's input from `answers`
        name: "URL",
        // Basic validation inside inquirer to prevent empty entries
        validate: (input) => {
          if (!input || input.trim() === "") return "Please enter a URL.";
          if (!isValidUrl(input)) return "Please enter a valid URL (include http:// or https://).";
          return true;
        },
      },
    ])
    .then((answers) => {
      // Extract the URL string the user entered from the answers object.
      const url = answers.URL;
      generateFromUrl(url);
    })
    .catch((error) => {
      // Handle errors from `inquirer.prompt`.
      if (error.isTtyError) {
        console.error("Interactive prompts are not supported in this environment.");
      } else {
        console.error("An error occurred while prompting:", error);
      }
    });
}

/*
Summary of what this script does:
1. Prompts the user to type a URL.
2. Converts that URL into a QR code image and writes it to `qr_img.png`.
3. Writes the original URL into `URL.txt` for record-keeping.
*/
