//Notes: All comments are AI generated for educational purposes.


// Array of the four button colours used in the game
var buttonColours = ["red", "blue", "green", "yellow"];

// `gamePattern` stores the sequence generated by the game
var gamePattern = [];
// `userClickedPattern` stores the buttons the user has clicked in the current level
var userClickedPattern = [];

// `started` tracks whether the game has begun; `level` stores the current level number
var started = false;
var level = 0;
// `hardMode` when true makes the game add TWO colours to the sequence every level.
// This implements a harder difficulty: the player must memorize two new colours each level
// in addition to the previous sequence. Default is `false` (normal mode: +1 colour/level).
var hardMode = false;

// Start the game when the user clicks the Play button (replaces keypress start)
$("#play-btn").click(function() {
  if (!started) {
    // Hide the top instructions once the player starts the game
    $("#instructions").hide();
    // Hide the Play button while the level is running
    $("#play-btn").hide();
    // Display the initial level and generate the first sequence
    $("#level-title").text("Level " + level);
    // Wait 1 second so the player has time to get ready, then show the sequence
    setTimeout(function() {
      nextSequence();
    }, 1000);
    started = true;
  }
});

// Hard Level button: toggle hard mode on/off and restart the game.
// When enabled, `hardMode = true` causes two new colours to be added each level.
$("#hard-btn").click(function() {
  // Toggle the hard mode flag
  hardMode = !hardMode;
  // Play the same sound as the blue pad when the button is pressed
  playSound("blue");

  if (hardMode) {
    // Switch to hard mode: update button label and instructions
    $("#hard-btn").text("Regular-Mode");
    $("#level-title").text("Hard Mode: Press Play to Start");
    $("#instructions").text("Hard mode: memorize 2 new colours each level").show();
  } else {
    // Switch back to regular mode: restore labels and instructions
    $("#hard-btn").text("Hard Level");
    $("#level-title").text("Press Play to Start");
    $("#instructions").text("Watch the sequence, then repeat it by clicking the colored pads.").show();
  }

  // Reset game state so the player can begin a fresh game under the selected mode
  startOver();
});

// Handle user clicks on any of the coloured buttons
$(".btn").click(function() {

  // Determine which button was clicked by reading its `id`
  var userChosenColour = $(this).attr("id");
  // Record the user's choice in the pattern for this round
  userClickedPattern.push(userChosenColour);

  // Provide immediate feedback: play the corresponding sound and animate the press
  playSound(userChosenColour);
  animatePress(userChosenColour);

  // Check the user's answer: compare the most recent click to the game pattern
  checkAnswer(userClickedPattern.length-1);
});

// checkAnswer compares the user's input to the game sequence at `currentLevel`
function checkAnswer(currentLevel) {

    // If the most recent user choice matches the game pattern
    if (gamePattern[currentLevel] === userClickedPattern[currentLevel]) {
      // If the user has completed the current sequence correctly, proceed to next level
      if (userClickedPattern.length === gamePattern.length){
        setTimeout(function () {
          nextSequence();
        }, 1000);
      }
    } else {
      // Wrong answer: play the wrong sound, show game-over visual, and prompt restart
      playSound("wrong");
      $("body").addClass("game-over");

      // Compose a message that includes the level the player reached.
      var reachedMsg = "Game Over — You reached Level " + level + ". Press Play to Restart";
      if (hardMode) {
        // Indicate hard mode in the message when active
        reachedMsg = "Game Over — You reached Level " + level + " (Hard). Press Play to Restart";
      }
      $("#level-title").text(reachedMsg);

      // Briefly flash the game-over class for visual feedback
      setTimeout(function () {
        $("body").removeClass("game-over");
      }, 200);

      // Reset game state so the player can restart
      startOver();
    }
}


// nextSequence advances the game by choosing a new random colour and showing it
function nextSequence() {
  // Reset the user's pattern for the new level
  userClickedPattern = [];
  // Ensure Play button is hidden while the sequence is shown
  $("#play-btn").hide();
  // Increase the level counter and update the heading
  level++;
  $("#level-title").text("Level " + level);
  // Pick a random index to select a colour
  // In normal mode: add one new random colour to the sequence.
  // In hard mode: add TWO new random colours to the sequence each level,
  // which the player must memorize in order along with previous colours.
  if (!hardMode) {
    var randomNumber = Math.floor(Math.random() * 4);
    var randomChosenColour = buttonColours[randomNumber];
    gamePattern.push(randomChosenColour);
  } else {
    // Add two colours for hard mode
    for (var k = 0; k < 2; k++) {
      var rn = Math.floor(Math.random() * 4);
      gamePattern.push(buttonColours[rn]);
    }
  }

  // Briefly animate the entire sequence so far (show each colour in order)
  for (var i = 0; i < gamePattern.length; i++) {
    (function(col, idx) {
      setTimeout(function() {
        $("#" + col).fadeIn(100).fadeOut(100).fadeIn(100);
        playSound(col);
      }, idx * 600);
    })(gamePattern[i], i);
  }
}

// animatePress adds a temporary 'pressed' class for button press animation
function animatePress(currentColor) {
  $("#" + currentColor).addClass("pressed");
  setTimeout(function () {
    $("#" + currentColor).removeClass("pressed");
  }, 100);
}

// playSound loads and plays the named sound file from the `sounds` folder
function playSound(name) {
  var audio = new Audio("sounds/" + name + ".mp3");
  audio.play();
}

// startOver resets game variables to allow a fresh start
function startOver() {
  level = 0;
  gamePattern = [];
  started = false;
  // Show the top instructions again so the player knows how to restart
  $("#instructions").show();
  // Reveal the Play button so the player can start again
  $("#play-btn").show();
  // When starting over we do not automatically clear hardMode — the player can
  // toggle it using the Hard Level button. If you want hardMode to reset on
  // restart, set `hardMode = false;` here.
}
